#!/usr/bin/env bash

###############################################################################

NORMAL=0
BOLD=1
UNDERLINE=4
RED=31
GREEN=32
BROWN=33
BLUE=34
MAGENTO=35
CYAN=36
GREY=37

CL_NORM="\e[${NORM}m"
CL_BOLD="\e[${BOLD}m"
CL_UNLN="\e[${UNLN}m"
CL_RED="\e[${RED}m"
CL_GREEN="\e[${GREEN}m"
CL_BROWN="\e[${BROWN}m"
CL_BLUE="\e[${BLUE}m"
CL_MAG="\e[${MAG}m"
CL_CYAN="\e[${CYAN}m"
CL_GREY="\e[${GREY}m"
CL_BL_RED="\e[${RED};1m"
CL_BL_GREEN="\e[${GREEN};1m"
CL_BL_BROWN="\e[${BROWN};1m"
CL_BL_BLUE="\e[${BLUE};1m"
CL_BL_MAG="\e[${MAG};1m"
CL_BL_CYAN="\e[${CYAN};1m"
CL_BL_GREY="\e[${GREY};1m"
CL_UL_RED="\e[${RED};4m"
CL_UL_GREEN="\e[${GREEN};4m"
CL_UL_BROWN="\e[${BROWN};4m"
CL_UL_BLUE="\e[${BLUE};4m"
CL_UL_MAG="\e[${MAG};4m"
CL_UL_CYAN="\e[${CYAN};4m"
CL_UL_GREY="\e[${GREY};4m"
CL_BG_RED="\e[${RED};7m"
CL_BG_GREEN="\e[${GREEN};7m"
CL_BG_BROWN="\e[${BROWN};7m"
CL_BG_BLUE="\e[${BLUE};7m"
CL_BG_MAG="\e[${MAG};7m"
CL_BG_CYAN="\e[${CYAN};7m"
CL_BG_GREY="\e[${GREY};7m"

###############################################################################

show() {
    if [[ -n "$2" && -z "$no_colors" ]] ; then
        echo -e "\e[${2}m${1}\e[0m"
    else
        echo -e "$1"
    fi
}

usage () {
    show "${CL_BOLD}Usage:${CL_NORM} repoview-generator ${CL_GREEN}<repopath>${CL_NORM}"
}

main () {
    local repo="$1"

    if [[ -n "$repo" ]] ; then
        for dir in `find "$repo" -name 'repodata' -type d`; do
            dir=$(dirname $dir)
            repoview -q "$dir"
            if [[ $? -eq 0 ]] ; then
                show "${CL_CYAN}$dir${CL_NORM} ${CL_GREEN}done${CL_NORM}"
            else
                show "${CL_CYAN}$dir${CL_NORM} ${CL_RED}fail${CL_NORM}"
            fi
        done
    else
        usage
    fi
}

###############################################################################

main $@
